### PR TITLE
Public facing event value limitations 

### PR DESCRIPTION
**Pull request by twodayslate**
Let me know if I need to make any changes, missed anything, or have any recommendations. I didn't see the need to add any test cases as the current ones seemed fine.

### CODE REVIEW

**Comment by TroubleMakerBen** [comment]
Hey Zac,

Thanks for the contribution! =)

We'd like to know more about the why of this. Why are you interested in reading the properties for events? Are you truncating your event names dynamically at runtime?

Best,
Benjamin

**Comment by twodayslate** [comment]
@TroubleMakerBen yes, that is what I am doing. That way I control how my string is truncated.

**Comment by jaelim-ms** [comment]
Triggering CI build

**Comment by twodayslate** [comment]
@TroubleMakerBen example property values could be a filename, stack trace, method name... all of which could go above the value length requirement and be truncated.  I could come up with more examples if you need but I don't see why these aren't exposed to the user anyway as they are referenced in the documentation.

**Comment by jaelim-ms** [comment]
@twodayslate We consider all warnings as errors. The failure is caused by warnings.

```
2018-01-09T01:37:28.2516470Z ❌  /Users/vsts/agent/2.126.0/work/1/s/AppCenterAnalytics/AppCenterAnalytics/MSAnalytics.m:162:29: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
2018-01-09T01:37:28.2522840Z 
2018-01-09T01:37:28.2533490Z                  eventName, [MSAnalytics maxEventNameLength]);
2018-01-09T01:37:28.2544730Z                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-01-09T01:37:28.2550390Z 
2018-01-09T01:37:28.2558490Z 
2018-01-09T01:37:28.2564610Z 
2018-01-09T01:37:28.2576730Z ❌  /Users/vsts/agent/2.126.0/work/1/s/AppCenterAnalytics/AppCenterAnalytics/MSAnalytics.m:178:29: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
2018-01-09T01:37:28.2583160Z 
2018-01-09T01:37:28.2594060Z                    logName, [MSAnalytics maxPropertiesPerEvent]);
2018-01-09T01:37:28.2604900Z                        ^~~~~~~~
2018-01-09T01:37:28.2610360Z 
2018-01-09T01:37:28.2616290Z 
2018-01-09T01:37:28.2621710Z 
2018-01-09T01:37:28.2633630Z ❌  /Users/vsts/agent/2.126.0/work/1/s/AppCenterAnalytics/AppCenterAnalytics/MSAnalytics.m:195:46: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
2018-01-09T01:37:28.2640950Z 
2018-01-09T01:37:28.2651880Z                    logType, logName, strKey, [MSAnalytics maxPropertyKeyLength]);
2018-01-09T01:37:28.2662990Z                        ^~~~~~~~
2018-01-09T01:37:28.2668420Z 
2018-01-09T01:37:28.2673730Z 
2018-01-09T01:37:28.2679210Z 
2018-01-09T01:37:28.2691650Z ❌  /Users/vsts/agent/2.126.0/work/1/s/AppCenterAnalytics/AppCenterAnalytics/MSAnalytics.m:204:46: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
2018-01-09T01:37:28.2698070Z 
2018-01-09T01:37:28.2708850Z                    logType, logName, strKey, [MSAnalytics maxPropertyValueLength]);
2018-01-09T01:37:28.2719730Z                        ^~~~~~~~
```

**Comment by twodayslate** [comment]
Fixed. The only warnings I see in my Xcode workspace is "Validate Project Settings/Update to recommended Settings"

**Comment by jaelim-ms** [comment]
The SDK does not officially support building in Xcode 9. We are still building the SDK in Xcode 8.3.3 so you will see those warnings if you are building the SDK in Xcode 9.

**Comment by TroubleMakerBen** [comment]
@twodayslate 
This sounds like you are using `trackEvent` to track errors or exceptions?

**Comment by twodayslate** [comment]
Amount other things. The example event in the documentation uses a file name as a property as well.

-Zac on his iPhone

**Comment by TroubleMakerBen** [comment]
Hey Zachary,

Okay, we've discussed this with the team and we won't merge this PR. I want to take the time and explain why.

The PR itself looks good and there's no issue with the quality. I also understand the use-case. The reason why we're not merging this is that we have a bunch of changes coming up that would require us to refactor the PR as they will very likely require to add an API for this or something very similar across all different modules (Crash, Distribute, even Push). Adding your API will require us to carry it around for a long time which we don't want, especially as we'd need to add the API to all our other SDKs for consistency.

I hope you understand this and are okay with hardcoding the values instead of getting them from the SDK.

Best,
Benjamin

**Comment by twodayslate** [comment]
Thanks for the explanation. Sounds like there are some very interesting changes coming.

Cheers

-Zac on his iPhone

**Pull request closed without merging**
