### PR TITLE
Ensure that -[NSApplication isHidden] is called from the main thread

### LINKED ISSUE #1705: `+[MSUtility(Application) sharedAppState]` must be called from the main thread
https://github.com/microsoft/appcenter-sdk-apple/blob/d3eb6c942c39be49a6363f28c86f799eb5c1f5c0/AppCenter/AppCenter/Internals/Util/MSUtility%2BApplication.m#L50

This line is tripping the main thread UI checker when called from `-[MSCrashes startDelayedCrashProcessing]`: 

```
=================================================================
Main Thread Checker: UI API called on a background thread: -[NSApplication isHidden]
PID: 61170, TID: 516248, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   Reveal                              0x0000000100701cb4 +[MSUtility(Application) sharedAppState] + 53
5   Reveal                              0x000000010066e60c -[MSCrashes startCrashProcessing] + 61
6   Reveal                              0x000000010066e512 __40-[MSCrashes startDelayedCrashProcessing]_block_invoke + 33
7   libdispatch.dylib                   0x00007fff6c79c5de _dispatch_client_callout + 8
8   libdispatch.dylib                   0x00007fff6c79e790 _dispatch_continuation_pop + 414
9   libdispatch.dylib                   0x00007fff6c7ae430 _dispatch_source_invoke + 2084
10  libdispatch.dylib                   0x00007fff6c79e2d2 _dispatch_queue_override_invoke + 421
11  libdispatch.dylib                   0x00007fff6c7aa8e5 _dispatch_root_queue_drain + 326
12  libdispatch.dylib                   0x00007fff6c7ab025 _dispatch_worker_thread2 + 92
13  libsystem_pthread.dylib             0x00007fff6c9fb699 _pthread_wqthread.cold.1 + 67
14  libsystem_pthread.dylib             0x00007fff6c9f5856 _pthread_wqthread + 203
15  libsystem_pthread.dylib             0x00007fff6c9f5717 start_wqthread + 15
```

### PR DESCRIPTION
**Pull request by tonyarnold**
Fixes #1705

### CODE REVIEW

**Comment by tomquist** [comment]
@MatkovIvan What's your suggestion on how to fix the issue?

**Comment by MatkovIvan** [comment]
@tomquist 
It requires a little more attention, I'm not ready to say the final solution right now.
No worries, this issue is in our board, we'll take care of it.

**Comment by tonyarnold** [comment]
@MatkovIvan it would have been nice if you could have provided some direction around the expected approach when you rejected it. I understand why this can cause deadlocks, however the same pattern is used elsewhere within this project to achieve the same outcome. I assume here, however, there is a chance this will be called in a nested `dispatch_sync` given how often the `sharedAppState` class method is called?

This API misuse is tripping the main thread checker in Xcode, causing all of my team's CI builds to fail. How is it not tripping CI for this project?

**Comment by tonyarnold** [comment]
Also, if the pull request template is _required_ please make that clear. Right now, it sounds like a personal checklist that I just need to verify before the PR will be merged: "Things to consider before you submit the PR".

**Comment by MatkovIvan** [comment]
Hi @tonyarnold,

I've created a PR with fix for that - #1712
My approach is still under discussion, so feel free to review/leave comments.

> it would have been nice if you could have provided some direction around the expected approach when you rejected it

The problem was I didn't have ready solution at that moment. Some generic ways are 
- move all calls to main thread (is not possible for this case)
- return error or blank value when it called from inappropriate thread (that's what my PR do)
- subscribe to change state events for keep some value that we can read later (overengineering for this case imho)

> this will be called in a nested `dispatch_sync`

No, it's because of this semaphore:
https://github.com/microsoft/appcenter-sdk-apple/blob/4bea6348f2f0b4c51898c86d50302e59888931f1/AppCenterCrashes/AppCenterCrashes/MSCrashes.mm#L150-L153

> How is it not tripping CI for this project?

I'm not sure why but I can't get this warning even after enabling thread checking flags (both in tests and in applications)

> if the pull request template is _required_ please make that clear. Right now, it sounds like a personal checklist that I just need to verify before the PR will be merged

It isn't strict _requirement_ but it should help authors remember to check that unit tests pass etc.
Anyway, thank you for feedback we'll discuss template improvement.

**Pull request closed without merging**
